### ISSUE TITLE
is there a work around to to select vst fx settings once a midi playlist instead of selecting it every time again?

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/Keppys-MIDI-Converter#46]
is there a work around to to select vst fx settings once a midi playlist instead of selecting it every time again?

**Comment by KaleidonKep99** [comment]
I'll see what I can do about it.

**Comment by ewewo2** [comment]
hi on 18.1.3 is a lil bug... the fx will only be processed on the first file

**Comment by KaleidonKep99** [comment]
I'll see what the issue is later.

**Comment by KaleidonKep99** [comment]
I tried reproducing the issues, but all the VSTs get applied to the entire conversion queue, on both conversion and playback mode.

**Comment by ewewo2** [comment]
i re-checked it on different pc's - some vsts work, some others are only applied on the first file. i'll pm you a license of a plugin, which does only work on the first file.

**Comment by ewewo2** [comment]
i mailed to your outlook adress, the subject is "plugin license"

**Comment by ewewo2** [comment]
the rendering time of the wave files varies:
first midi files is 5-6x speed
all others are 32x speed

**Comment by KaleidonKep99** [comment]
Sharing VST licenses is against their EULA, I can't test it. I deleted the e-mail from my inbox.
I'll try and search for some free VSTs that exhibit the same behavior.

**Comment by ewewo2** [comment]
The error also occurs in the trial Version

**Comment by KaleidonKep99** [comment]
Oh alright, what's the name of the plug-in again? I deleted the e-mail and I don't remember.

**Comment by ewewo2** [comment]
toontrack ezmix

**Comment by KaleidonKep99** [comment]
I see what the issue is. I'll try to fix it now.

**Comment by KaleidonKep99** [comment]
Looks like EZMix 2 doesn't support presets.
I tried every way I could think of, to get it to work:
- Copy the parameters from a dummy VST to the one tied to the audio stream
- Create a session of the chunk, and copy it whenever the VST got destroyed (Turns out the VST doesn't support chunks...)
- Store the parameters myself, and set them one by one when a new MIDI has to be converted

I blame the developer of the VST for this. Sorry but I can't fix this issue.
